import org.gradle.api.artifacts.VersionCatalogsExtension
import org.jlleitschuh.gradle.ktlint.KtlintExtension
import org.jlleitschuh.gradle.ktlint.reporter.ReporterType
import java.awt.RenderingHints
import java.awt.image.BufferedImage
import javax.imageio.ImageIO

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.android.junit5) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.ktlint) apply false
    alias(libs.plugins.jraska.module.graph.assertion)
}

val ktlintVersion: String = extensions
    .getByType<VersionCatalogsExtension>()
    .named("libs")
    .findVersion("ktlint")
    .get()
    .requiredVersion

moduleGraphAssert {
    // Only production dependencies count as architecture: a feature's tests may reach core:testing
    configurations = setOf("api", "implementation")
    // :app is the composition root and the only module allowed to see features.
    // Features never see each other: they talk through :core:navigation routes and shared
    // :core:* state. :ui:* is presentation-only and knows nothing about features or data.
    // :core:navigation is the one core module that may reach :ui (its command collector is a
    // composable). Nothing depends on :app.
    restricted = arrayOf(
        ":feature:.* -X> :feature:.*",
        ":core:.* -X> :feature:.*",
        ":ui:.* -X> :feature:.*",
        ":ui:.* -X> :core:.*",
        ":core:(?!navigation).* -X> :ui:.*",
        ".* -X> :app",
    )
}

subprojects {
    apply(plugin = "org.jlleitschuh.gradle.ktlint")

    if (path != ":tools:ktlint-custom-rules") {
        dependencies {
            add("ktlintRuleset", project(":tools:ktlint-custom-rules"))
        }
    }

    extensions.configure<KtlintExtension> {
        version.set(ktlintVersion)
        debug.set(false)
        verbose.set(true)
        outputToConsole.set(true)
        ignoreFailures.set(false)
        enableExperimentalRules.set(false)

        filter {
            exclude("**/generated/**")
            exclude("**/build/**")
            include("**/kotlin/**")
        }

        reporters {
            reporter(ReporterType.CHECKSTYLE)
        }
    }
}

// The README's screenshots are generated by the Robolectric generators in :tools:screenshots and
// versioned under docs/screenshots/, so a reader sees the app without running anything. The
// notification shot is the one exception: the system shade is not a composable, so it stays a
// manual capture. See docs/screenshots.md.
private val generatedScreenshotsPath = "outputs/screenshots"
private val readmeScreenshotWidth = 520
private val manualScreenshots = setOf("notification.png")

private val clearGeneratedScreenshots = tasks.register<Delete>("clearGeneratedScreenshots") {
    delete(layout.buildDirectory.dir(generatedScreenshotsPath))
}

project(":tools:screenshots").tasks.matching { task -> task.name.startsWith("test") }.configureEach {
    dependsOn(clearGeneratedScreenshots)
}

tasks.register("updateReadmeScreenshots") {
    group = "screenshots"
    description = "Regenerates the screenshots the README shows and writes them to docs/screenshots/."
    dependsOn(":tools:screenshots:testDebugUnitTest")
    val generatedDir = layout.buildDirectory.dir("$generatedScreenshotsPath/en-US/images/readme")
    val screenshotsDir = layout.projectDirectory.dir("docs/screenshots")
    val targetWidth = readmeScreenshotWidth
    val manual = manualScreenshots
    doLast {
        // Drawn down in halving steps before the last one: a single draw from 1242px samples too
        // few of the pixels it skips and leaves hairlines and small text ragged.
        fun BufferedImage.renderAt(width: Int): BufferedImage {
            val height = (this.height.toLong() * width / this.width).toInt()
            val scaled = BufferedImage(width, height, BufferedImage.TYPE_INT_RGB)
            val graphics = scaled.createGraphics()
            graphics.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR)
            graphics.drawImage(this, 0, 0, width, height, null)
            graphics.dispose()
            return scaled
        }

        fun BufferedImage.renderScaledTo(width: Int): BufferedImage {
            var current = this
            while (current.width > width * 2) {
                current = current.renderAt(current.width / 2)
            }
            return if (current.width == width) current else current.renderAt(width)
        }

        val generated = generatedDir
            .get()
            .asFile
            .listFiles { file -> file.extension == "png" }
            .orEmpty()
            .sortedBy { png -> png.name }
        // Collected before anything is deleted: docs/screenshots/ is versioned, and a filtered run
        // that produced nothing would otherwise empty it and take the README's images with it.
        check(generated.isNotEmpty()) {
            "No screenshots were generated under ${generatedDir.get().asFile}."
        }
        // Wiped so a shot that was renamed or dropped cannot stay in the folder — and in the
        // README — forever.
        screenshotsDir
            .asFile
            .listFiles { file -> file.extension == "png" && file.name !in manual }
            .orEmpty()
            .forEach { png -> png.delete() }
        generated.forEach { png ->
            val scaled = ImageIO.read(png).renderScaledTo(targetWidth)
            ImageIO.write(scaled, "png", screenshotsDir.asFile.resolve(png.name))
        }
        logger.lifecycle("updateReadmeScreenshots: wrote ${generated.size} screenshot(s) into docs/screenshots/")
    }
}
