import org.gradle.api.artifacts.VersionCatalogsExtension
import org.jlleitschuh.gradle.ktlint.KtlintExtension
import org.jlleitschuh.gradle.ktlint.reporter.ReporterType
import org.w3c.dom.Element
import java.awt.RenderingHints
import java.awt.image.BufferedImage
import javax.imageio.ImageIO
import javax.xml.parsers.DocumentBuilderFactory

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.android.junit5) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.ktlint) apply false
    alias(libs.plugins.jraska.module.graph.assertion)
    alias(libs.plugins.kover)
}

val ktlintVersion: String = extensions
    .getByType<VersionCatalogsExtension>()
    .named("libs")
    .findVersion("ktlint")
    .get()
    .requiredVersion

moduleGraphAssert {
    // Only production dependencies count as architecture: a feature's tests may reach core:testing
    configurations = setOf("api", "implementation")
    // :app is the composition root and the only module allowed to see features.
    // Features never see each other: they talk through :core:navigation routes and shared
    // :core:* state. :ui:* is presentation-only and knows nothing about features or data.
    // :core:navigation is the one core module that may reach :ui (its command collector is a
    // composable). Nothing depends on :app. A :core:*:impl module is wired by :app alone;
    // everyone else sees the interfaces in the matching :core:*:api.
    restricted = arrayOf(
        ":feature:.* -X> :feature:.*",
        ":core:.* -X> :feature:.*",
        ":ui:.* -X> :feature:.*",
        ":ui:.* -X> :core:.*",
        ":core:(?!navigation).* -X> :ui:.*",
        ":feature:.* -X> :core:.*:impl",
        ":core:.* -X> :core:.*:impl",
        ":tools:.* -X> :core:.*:impl",
        ".* -X> :app",
    )
}

// The root merges every module that applies Kover (configureCoverage in build-logic) into one
// report, decides what counts as coverable code and sets the bar. It lives here and not in a
// convention plugin because applying anything from build-logic at the root puts the convention
// plugins on every module's classpath, and their `version = "unspecified"` aliases stop resolving.
private val coverageVariant = "ci"
private val coverageMinPercent = 80

kover {
    // The variant has to exist here too, even though the root has no sources of its own
    currentProject {
        createVariant(coverageVariant) {}
    }
    reports {
        filters {
            excludes {
                // Composables are covered on device by the androidTest suites
                annotatedBy(
                    "androidx.compose.runtime.Composable",
                    "androidx.compose.ui.tooling.preview.Preview",
                )
                // The annotation leaves behind the top-level Dp constants of the composable-only
                // packages, which no unit test can reach either
                packages("*.presentation.content", "*.presentation.component")
                // Navigation entries and Koin modules are wiring, with no behaviour of their own
                packages("*.presentation.navigation", "*.di")
                // The Glance widgets, their receivers and their action callbacks: RemoteViews
                // plumbing the AppWidget host drives, with nothing a JVM test can reach
                packages("*.presentation.widget")
                // Generated by Room, kotlinx.serialization and the Compose compiler. `DefaultImpls`
                // is the shim the Kotlin compiler leaves beside an interface with a method body,
                // for Java callers only: the body itself is measured on the interface.
                classes(
                    "*_Impl",
                    "*_Impl$*",
                    "*$\$serializer",
                    "*ComposableSingletons$*",
                    "*\$DefaultImpls",
                )
            }
        }
        verify {
            rule("Line coverage of the merged report") {
                minBound(coverageMinPercent)
            }
        }
    }
}

// The merged rule is an average, so a new file with no tests barely moves it. This holds every
// file a change adds to the same bar on its own. Files the filters above exclude are not in the
// report and are skipped, and so are files with nothing to execute (interfaces, plain models).
tasks.register("verifyNewFilesCoverage") {
    group = "verification"
    description = "Fails when a file added since coverage.baseRef (origin/main) is under the coverage bar."
    val variantSuffix = coverageVariant.replaceFirstChar { char -> char.uppercase() }
    dependsOn("koverXmlReport$variantSuffix")
    val report = layout.buildDirectory.file("reports/kover/report$variantSuffix.xml")
    val baseRef = providers.gradleProperty("coverage.baseRef").orElse("origin/main")
    // Against the working tree rather than HEAD, so a local run also sees files staged with git add
    val addedFiles = providers
        .exec { commandLine("git", "diff", "--name-only", "--diff-filter=A", baseRef.get()) }
        .standardOutput
        .asText
        .map { output -> output.lines().filter { path -> path.endsWith(".kt") } }
    val minPercent = coverageMinPercent
    doLast {
        val factory = DocumentBuilderFactory.newInstance()
        // The report names a DTD that is not on disk, and the parser would otherwise try to load it
        factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false)
        val sourceFiles = factory.newDocumentBuilder().parse(report.get().asFile).getElementsByTagName("sourcefile")
        // "<package path>/<File>.kt" to (covered, total) lines
        val linesBySource = (0 until sourceFiles.length)
            .map { index -> sourceFiles.item(index) as Element }
            .groupBy { sourceFile ->
                "${(sourceFile.parentNode as Element).getAttribute("name")}/${sourceFile.getAttribute("name")}"
            }.mapValues { (_, sameSource) ->
                val counters = sameSource.map { sourceFile ->
                    val children = sourceFile.childNodes
                    (0 until children.length)
                        .map { index -> children.item(index) }
                        .filterIsInstance<Element>()
                        .first { child -> child.tagName == "counter" && child.getAttribute("type") == "LINE" }
                }
                val covered = counters.sumOf { counter -> counter.getAttribute("covered").toInt() }
                covered to covered + counters.sumOf { counter -> counter.getAttribute("missed").toInt() }
            }
        val measured = addedFiles.get().mapNotNull { path ->
            val source = path.substringAfter("/src/main/kotlin/", missingDelimiterValue = "")
            linesBySource[source]?.let { lines -> path to lines }
        }
        val belowTheBar = measured.filter { (_, lines) -> lines.first * 100 < minPercent * lines.second }
        logger.lifecycle(
            "verifyNewFilesCoverage: ${measured.size} new measured file(s), ${belowTheBar.size} below $minPercent%",
        )
        if (belowTheBar.isNotEmpty()) {
            val details = belowTheBar.joinToString(separator = "\n") { (path, lines) ->
                "  ${lines.first * 100 / lines.second}% (${lines.first}/${lines.second} lines)  $path"
            }
            throw GradleException("New files must have at least $minPercent% line coverage:\n$details")
        }
    }
}

subprojects {
    apply(plugin = "org.jlleitschuh.gradle.ktlint")

    val module = this
    pluginManager.withPlugin("org.jetbrains.kotlinx.kover") {
        rootProject.dependencies.add("kover", module)
    }

    if (path != ":tools:ktlint_custom_rules") {
        dependencies {
            add("ktlintRuleset", project(":tools:ktlint_custom_rules"))
        }
    }

    extensions.configure<KtlintExtension> {
        version.set(ktlintVersion)
        debug.set(false)
        verbose.set(true)
        outputToConsole.set(true)
        ignoreFailures.set(false)
        enableExperimentalRules.set(false)

        filter {
            exclude("**/generated/**")
            exclude("**/build/**")
            include("**/kotlin/**")
        }

        reporters {
            reporter(ReporterType.CHECKSTYLE)
        }
    }
}

// The README's screenshots are generated by the Robolectric generators in :tools:screenshots and
// versioned under docs/screenshots/, so a reader sees the app without running anything. The
// notification shot is the one exception: the system shade is not a composable, so it stays a
// manual capture. See docs/screenshots.md.
private val generatedScreenshotsPath = "outputs/screenshots"
private val readmeScreenshotWidth = 520
private val manualScreenshots = setOf("notification.png")

private val clearGeneratedScreenshots = tasks.register<Delete>("clearGeneratedScreenshots") {
    delete(layout.buildDirectory.dir(generatedScreenshotsPath))
}

project(":tools:screenshots").tasks.matching { task -> task.name.startsWith("test") }.configureEach {
    dependsOn(clearGeneratedScreenshots)
}

tasks.register("updateReadmeScreenshots") {
    group = "screenshots"
    description = "Regenerates the screenshots the README shows and writes them to docs/screenshots/."
    dependsOn(":tools:screenshots:testDebugUnitTest")
    val generatedDir = layout.buildDirectory.dir("$generatedScreenshotsPath/en-US/images/readme")
    val screenshotsDir = layout.projectDirectory.dir("docs/screenshots")
    val targetWidth = readmeScreenshotWidth
    val manual = manualScreenshots
    doLast {
        // Drawn down in halving steps before the last one: a single draw from 1242px samples too
        // few of the pixels it skips and leaves hairlines and small text ragged.
        fun BufferedImage.renderAt(width: Int): BufferedImage {
            val height = (this.height.toLong() * width / this.width).toInt()
            val scaled = BufferedImage(width, height, BufferedImage.TYPE_INT_RGB)
            val graphics = scaled.createGraphics()
            graphics.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR)
            graphics.drawImage(this, 0, 0, width, height, null)
            graphics.dispose()
            return scaled
        }

        fun BufferedImage.renderScaledTo(width: Int): BufferedImage {
            var current = this
            while (current.width > width * 2) {
                current = current.renderAt(current.width / 2)
            }
            return if (current.width == width) current else current.renderAt(width)
        }

        val generated = generatedDir
            .get()
            .asFile
            .listFiles { file -> file.extension == "png" }
            .orEmpty()
            .sortedBy { png -> png.name }
        // Collected before anything is deleted: docs/screenshots/ is versioned, and a filtered run
        // that produced nothing would otherwise empty it and take the README's images with it.
        check(generated.isNotEmpty()) {
            "No screenshots were generated under ${generatedDir.get().asFile}."
        }
        // Wiped so a shot that was renamed or dropped cannot stay in the folder — and in the
        // README — forever.
        screenshotsDir
            .asFile
            .listFiles { file -> file.extension == "png" && file.name !in manual }
            .orEmpty()
            .forEach { png -> png.delete() }
        generated.forEach { png ->
            val scaled = ImageIO.read(png).renderScaledTo(targetWidth)
            ImageIO.write(scaled, "png", screenshotsDir.asFile.resolve(png.name))
        }
        logger.lifecycle("updateReadmeScreenshots: wrote ${generated.size} screenshot(s) into docs/screenshots/")
    }
}
