plugins {
    alias(libs.plugins.tunescout.android.application)
    alias(libs.plugins.androidx.baselineprofile)
}

android {
    namespace = "com.pierre.tunescout"

    defaultConfig {
        applicationId = "com.pierre.tunescout"
        versionCode = 1
        versionName = "1.0.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }
}

// The profile is generated by :tools:baselineprofile on a device and committed under
// src/main/generated/baselineProfiles, so a plain build packages it without a device attached.
// See docs/performance.md.
baselineProfile {
    automaticGenerationDuringBuild = false
    saveInSrc = true
    mergeIntoMain = true
    // Also writes a startup profile, which R8 uses to lay out the classes a cold start loads in the
    // primary dex file
    dexLayoutOptimization = true
}

dependencies {
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.profileinstaller)
    implementation(libs.coil.singleton)
    implementation(libs.coil.network.ktor)

    implementation(projects.core.model)
    implementation(projects.core.utils)
    implementation(projects.core.navigation)
    implementation(projects.core.network.api)
    implementation(projects.core.network.impl)
    implementation(projects.core.database.api)
    implementation(projects.core.database.impl)
    implementation(projects.core.datastore)
    implementation(projects.core.playback.api)
    implementation(projects.core.playback.impl)
    implementation(projects.ui.theme)
    implementation(projects.ui.component)
    implementation(projects.ui.utils)

    implementation(projects.feature.songs)
    implementation(projects.feature.library)
    implementation(projects.feature.songOptions)
    implementation(projects.feature.miniPlayer)
    implementation(projects.feature.player)
    implementation(projects.feature.queue)
    implementation(projects.feature.album)
    implementation(projects.feature.themeSelection)
    implementation(projects.feature.addToPlaylist)
    implementation(projects.feature.audioSearch)
    implementation(projects.feature.widget)

    baselineProfile(projects.tools.baselineprofile)

    testImplementation(libs.koin.test)
    testImplementation(projects.core.testing)
    androidTestImplementation(projects.core.testing)
}
